export const server = "http://127.0.0.1:8000/"
export const dlearn = "admin/dlearn/"
export const webcrawler = "admin/dlearn/webcrawler/"
export const nlp = "admin/nlp/"
export const moviere = "admin/nlp/imdb/"
export const loginre = "blog/auth/"